services:
  nginx:
    image: nginx:alpine
    container_name: app-converter-nginx
    restart: unless-stopped
    environment:
      - CLIENT_MAX_BODY_SIZE=20M
      - PHP_FPM_HOST=app:9000
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app
      - db

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: app-converter
    container_name: app-converter
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: app-converter-db
    restart: unless-stopped
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "converter-pgsql:/var/lib/postgresql/data"
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./docker/postgres/testing.sql:/docker-entrypoint-initdb.d/10-testing.sql
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}",
        ]
      retries: 3
      timeout: 5s
    ports:
      - 5432

volumes:
  converter-pgsql:
    driver: local
